### PR TITLE
Update requirements.txt, add installation instructions

### PR DESCRIPTION
**Pull request by ChrisFairless**
(Not urgent)

I'm not sure how everyone is managing their virtual environments, but I tried a reinstall recently with Conda and it didn't work.

Here's an updated requirement.txt and a short README giving installation instructions.

### CODE REVIEW

**Review by mastaia — APPROVED** [review]
Hey Chris, 
Thanks for this PR, do you know why the newest version did not work for you, because 4.0.2 does not seem to be the newest.

**Comment by mastaia** [comment]
Fix a certain version: 4.0.0, since 4.02. had major updated on cerntriods

**Comment by ChrisFairless** [comment]
@mastaia I've revamped the installation instructions to be ✨informative✨

**Comment by ChrisFairless** [comment]
Merging!
Also, for the record, I got the CLIMADA version number wrong earlier: v4.1.0 was the last release before the Centroids refactor. So that's what we'll use.

**Pull request merged**
