### PR TITLE
Implement business interruption for TC

### PR DESCRIPTION
**Pull request by ChrisFairless**
A second version of the previous attempt at BI (but not dependent on it)

- Add business_interruption.py to the direct impact calculations. This reads a CSV containing processed data from HAZUS to link asset damage to production loss in days and creates a CLIMADA impact function for the requested sector
- Add combine_impact_funcs.py to the direct impact calculations. This creates a new ImpactFuncComposable class based on CLIMADA's ImpactFunc with added methods that let you compose functions. Meaning you can combine two or more impact functions into a single function. Here it's for tropical cyclone wind -> % asset loss -> % production loss
- Add business interruption to the tropical cyclone hazard
- Add CLIMADA's regional impact functions to the tropical cyclone hazard

The improves on and replaces the work started in #18 which we can close now.

### CODE REVIEW

**Review by mastaia — APPROVED** [review]
Hi Chris,

We looked at the branch and also run the code. Looks good in my opinion. The values indeed get smaller as expected to the implementation of the BI functions. What is a bit surprising to me is that the order of the countries has slightly changed between the different runs. Also, the numbers decreased drastically for China and Japan, whereas for the US it is slightly smaller

with BI scaling:
image

without BI scaling:
image

From my point of view, we can merge it, but we first need to make sure that the resulting numbers are realistic. If we do not apply the scaling to the other hazards, TC will then be much smaller which in the end will change the interpretation work.

**Comment by ChrisFairless** [comment]
Yeah in hindsight it was dumb to add BI _and_ change the TC impact functions in the same PR.

I've just finished running a comparison using these new impact functions and with BI turned on and off, and I can post some results here.

For context, these are the new regional impact functions (taken from Eberenz et al https://nhess.copernicus.org/articles/21/393/2021 ). They are 'uncalibrated' still, but probably more similar to what our calibrated ones will look like.

image

Note that the USA and NW Pacific (i.e. Japan) have big drops in impacts compared to other locations.

Let's have a chat about what this means for interpretation because that's probably kind of important...

**Comment by ChrisFairless** [comment]
I think I want to add a 'include BI' option in the code somehow. Partly because we'll want to produce asset loss data as well as BI for our validation, partly so we can test without swapping between branches. Should that be another line in config.py? Or just something you turn on and off in analysis.py? (the latter would be faster to implement for now I guess...)

**Comment by mastaia** [comment]
Hi Chris, 
Thanks for the clarification. Indeed, it slipped me that there are also now some new regional modifiers in place. I think we should just be careful what we include now in this run and what not. It is a good idea to include a BI-switch. Let's maybe quickly discuss.

**Comment by mastaia** [comment]
Hi @ChrisFairless 

Here is again the number example I used for the validation. It definitely is not a fully valid proof of numbers but it gives some indication of how I could imagine to validate some numbers. 

**Focus: TC - USA - Manufacturing sector**
---------------------------------------------------
Some quick research

- total loss of 1.3 trillion (1'300'000'000'000) from 1980-2023  (Source: [NOAA](https://coast.noaa.gov/states/fast-facts/hurricane-costs.html)) --> very rough estimate of an average annual loss within the 43  years of about **30bn** (30'232'558'139)
- GDP US (2021): **23'000'000'000'000** (Source: [WorldBank](https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?end=2022&locations=US&most_recent_year_desc=true&start=1960))
- Based on the above two numbers the calculated TC damage of the annual GDP roughly gets 0.13%

- *11%* of the US GDP is roughly contributed by the manufacturing sector: (Source: [Statasia](https://www.statista.com/statistics/191972/value-added-by-us-manufacturing-as-a-percentage-of-gdp-since-2007/#:~:text=Value%20added%20of%20manufacturing%20as%20a%20percentage%20of%20GDP%202012%2D2020&text=In%202020%2C%20the%20manufacturing%20sector,sectors%20of%20the%20U.S.%20economy.))

--> Leading us to a calculated percentage of **0.0145%** (0.13% of 11%) of the manufacturing sector which gets shocked

-------------------------------------------------

Some Climada Output of the indirect impacts from the US shocked by TC in the manufacturing sector to CHE after the latest run:
- 0.27 Mio --> **270'000**
-------------------------------------------------

Again some research
-Raw Material & Semifinal products that get imported by Switzerland from the US make roughly 2'278'801'175 (Source: [SwissImpex](https://www.gate.ezv.admin.ch/swissimpex/public/bereiche/waren/query.xhtml)
- 270'000 from  2'278'801'175 make about **0.01%**


Therefore, if we assume a direct relationship between the shock in the US (**0.0145%**) and the impacts on the Swiss economy (270'000 which is about **0.01%** of the total manufacturing value we import from the US), the two percentage numbers are in the same order of magnitude. 

Not sure if this is now a lucky coincidence since, of course, the numbers used from the Swiss Impex reflect direct imports from the US to Switzerland, whereas the Climada impact model goes through the complete supply chain starting by impacting the US and then propagating the shock to Switzerland.

**Comment by ChrisFairless** [comment]
OK I've updated the code with a few new things:
- Added business interruption for all other hazards (but never apply it to the agriculture sector). As we discussed earlier, applying BI drops the calculated impacts by about a half, so it doesn't really work to apply it only to one hazard, since they'd be incomparable
- You can turn the BI on and off with a flag set at the start of direct.py
- The Utilities production loss impact function can go over 100%. This (for now) is capped to keep things simple. (This was actually introduced earlier, I forgot to point it out).

@mastaia I haven't looked into the results yet. If you have time, that would be great. Otherwise I'll do it Thursday!

**Comment by mastaia** [comment]
latest commit:

- Added: APPLY_BUSINESS_INTERRUPTION to True
- Added back the     if haz_type == 'RC':
        return agriculture.get_impf_set()
- Adjusted the test_config to make testing quicker

**Pull request merged**
