### PR TITLE
Add timestamp to output summary filenames

### PR DESCRIPTION
**Pull request by ChrisFairless**
The analysis chain writes a csv giving info on what it wanted to produce and what it was able to produce. Since the analysis.py might be run multiple times we decided to put a timestamp in the filename.

In addition this commit only writes the file out to one location, the `indirect_output_dir`. Earlier a copy was written to the both the direct and indirect dirs, but that's a bit confusing.

In addition a question on the file structures: right now we run the analysis and require the user to give both a direct and an indirect directory for results. I would propose providing a single directory and automatically writing to the direct/ and indirect/ subdirectories. Then things that don't belong to either (this output, the saved config object) can be written to the parent directory. I don't think this would break anything. Thoughts?

### CODE REVIEW

**Review by mastaia — COMMENTED** [review]
For me, the calculation report with the new timestamp is now only created in the indirect folder. Within the direct folder, no updates to the calculation report happen and no new calculation report is generated in the direct folder if a new run title is chosen. Is this intended? since the direct impact path is anyway referenced in the report?

Then I think, the report should go to the run folder and not to the indirect only 

image

**Comment by ChrisFairless** [comment]
I agree it's not very neat. I chose to output to the indirect folder (and not the direct _and_ indirect folders) because it felt weird to write out the file twice.

I would also prefer to add it to the run folder instead of the indirect folder. That would be much neater. But this starts a discussion about how we manage the folder structures in the project...

Currently analysis.py takes `direct_output_dir` and `indirect_output_dir` parameters in the `run_pipeline_from_config` method. Everything the script writes out is relative to these folders. (And if they're not supplied, it falls back on default paths defined in `utils.folder_naming`).

This means that in analysis.py we should avoid writing anything to the parent directory of `direct_output_dir` because we don't know for sure that it's a folder created for the results of this run (or that the direct and indirect directories share a parent folder). They _could_ be anywhere since the in/direct directories are user-supplied.

Except ... it has to be where we expect it to be, because elsewhere in the code we open files named with methods from `utils.folder_naming` which would fail if the script isn't running from the root directory of the repo.

So I would suggest getting rid of the `direct_output_dir` and `indirect_output_dir` input parameters altogether and instead use `utils.folder_naming` for all filepath and naming choices. Don't give the user any control beyond the name of the analysis. Then we can expect a more predictable directory structure and write things out as you suggest.

If you think that's reasonable I'll implement it.

**Comment by mastaia** [comment]
Hey Chris, 
I see. Actually, I like having the direct and indirect folders separately under the run title. And yes, I see. Direct and indirect anyway go together. So it is fine to only have it in the indirect folder. No need to change it from my point of view.

**Comment by ChrisFairless** [comment]
OK then I won't make any changes here. I'll merge this branch and make an issue so we keep track of the thing I mention above about analysis.py taking custom paths but the utils assuming we're running inside the repo base directory.

**Pull request merged**
